# Generated by Django 5.0 on 2023-12-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_cliente_created_cliente_updated_producto_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
