# Generated by Django 5.0 on 2023-12-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_alter_cliente_updated_alter_producto_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated',
        ),
    ]
